[package]
name = "systemicons"
version = "0.1.0"
authors = ["Uwe Riegel <uriegel@hotmail.de>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/uriegel/systemicons"
readme = "README.md"

[dependencies]
