[package]
name = "systemicons"
version = "0.1.0"
description = "With this lib you can retrive the system icon which is associated to a certain file extension. The icon will be in the .png format. Windows and Linux (GTK) are supperted."
authors = ["Uwe Riegel <uriegel@hotmail.de>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/uriegel/systemicons"
readme = "README.md"

[dependencies]
